name: Auto-Sync Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # This action happens when new changes happens in backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # History for all Code

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"

          git subtree split --prefix backend -b hf-deploy
          git branch -D hf-deploy 2>/dev/null || true
          git subtree split --prefix backend -b hf-deploy
