name: Auto-Sync Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # This action happens when new changes happens in backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # History for all Code

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create Backend Branch
        run: |
          git branch -D hf-deploy 2>/dev/null || true
          git subtree split --prefix backend -b hf-deploy

      - name: Push Backend to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://alokrj:${HF_TOKEN}@huggingface.co/spaces/alokrj/plant-disease-backend hf-deploy:main
          
